name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v2
        with:
          name: PeasAPI.dll
          path: PeasAPI/bin/Release/netstandard2.1/PeasAPI.dll
      
      - uses: actions/upload-artifact@v2
        with:
          name: PeasAPI.nupkg
          path: PeasAPI/bin/Release/PeasAPI.*.nupkg
